name: Rust

on:
  push:
    branches: ["main"]
  pull-request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt update; sudo apt install --no-install-recomends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
    - name: cargo build
      run: cargo build --release --verbose

        
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt update; sudo apt install --no-install-recomends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
    - name: run tests
      run: cargo tests -- --no-caputure
    

  fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: format
      run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt update; sudo apt install --no-install-recomends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
    - name: install clippy
      run: rustup component add clippy
    - name: run clippy
      run: cargo clippy -- -W clippy:pedantic --deny "warnings" 
    
